name: Update VLESS List

on:
  schedule:
    - cron: '0 */6 * * *' # Запуск каждые 6 часов
  workflow_dispatch: # Возможность ручного запуска

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run filter
        run: python filter.py

      - name: Commit changes
        run: |
          git config --global user.name "VLESS-Bot"
          git config --global user.email "bot@github.com"
          git pull origin main --rebase
          git add valid_vless.txt
          git commit -m "Auto-update: $(date)" || exit 0
          git push origin main

