name: Update VLESS List
on:
  schedule:
    - cron: '0 */6 * * *'
  workflow_dispatch:

jobs:
  filter_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: pip install requests PySocks


      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests

      - name: Run filter script
        run: python filter.py

      - name: Run Filter and Rename
        run: |
          python filter.py
          python rename.py
          
      - name: Commit and Push
        run: |
          git config --global user.name "VLESS-Bot"
          git config --global user.email "bot@github.com"
          git add valid_vless.txt
          git commit -m "Update list: 🇧🇬Bulgaria-№X style" || exit 0
          git push origin main
