name: Update VLESS List

on:
  schedule:
    # Запуск в 05 минут каждого часа (01:05, 02:05 и т.д.)
    - cron: '5 * * * *'
  workflow_dispatch: # Возможность запустить кнопкой вручную

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run filter
        run: python filter.py

      - name: Commit and Push changes
        run: |
          git config --global user.name "VLESS-Bot"
          git config --global user.email "bot@github.com"
          git add valid_vless.txt
          
          # Если файл не изменился, скрипт просто завершится без ошибки
          git commit -m "Hourly sync: $(date)" || exit 0
          
          git pull origin main --rebase -X theirs
          git push origin main
